"""Render an action-first, offline HTML view of the application ledger."""
from datetime import datetime, timedelta, timezone
from html import escape
from pathlib import Path
from urllib.parse import urlsplit

STATUS = {"candidate": "待了解", "ready": "待申请", "draft": "草稿", "submitted": "已提交", "assessment": "测评 / 笔试", "interview": "面试", "waiting": "待反馈", "offer": "Offer 待决定", "rejected": "未通过", "withdrawn": "已放弃", "signed": "已签约"}
KINDS = {"deadline": "官方截止", "scheduled": "官方安排", "suggested": "建议时间"}
SOURCES = {"employer": "企业官方", "school": "学校就业网", "personal_notice": "通知 / 凭证", "community": "社区线索", "other": "其他"}
MATERIALS = {"jd": "岗位要求", "resume": "本次已发简历", "experience": "相关经历", "interview": "准备与复盘", "offer": "录用条件"}
CLOSED = {"rejected", "withdrawn", "signed"}
CANDIDATES = {"candidate", "ready", "draft"}
MARKER = "<!-- generated by job-prep-kit dashboard -->"


def link(label, value, workspace, missing_hint=True):
    """Escape imported text and allow only explicit web or existing local files."""
    value = str(value)
    try:
        parsed = urlsplit(value)
    except ValueError:
        return escape(label)
    if parsed.scheme in {"http", "https"} and parsed.netloc:
        href = value
    else:
        path = Path(value)
        if (parsed.scheme and not path.is_absolute()) or value.startswith(("\\\\", "//")):
            return escape(label)
        path = path if path.is_absolute() else workspace / path
        if not path.is_file():
            return f'<span class="muted">{escape(label)} · 文件待补</span>' if missing_hint else escape(label)
        href = path.resolve().as_uri()
    return f'<a href="{escape(href, quote=True)}" rel="noreferrer">{escape(label)}</a>'


def date_label(value, now, relative=False):
    when = datetime.fromisoformat(value)
    local_now = now.astimezone(when.tzinfo)
    days = (when.date() - local_now.date()).days
    prefix = {0: "今天", 1: "明天", 2: "后天"}.get(days) if relative else None
    prefix = prefix or when.strftime("%m月%d日" if when.year == local_now.year else "%Y年%m月%d日")
    zone = when.strftime("%z")
    return f'<time datetime="{escape(value, quote=True)}" title="UTC{zone[:3]}:{zone[3:]}">{prefix} {when:%H:%M}</time>'


def material_links(app, workspace):
    return "".join(link(MATERIALS.get(key, key), value, workspace) for key, value in app.get("materials", {}).items())


def pending_events(app):
    return sorted((event for event in app["events"] if not event.get("done")), key=lambda e: datetime.fromisoformat(e["at"]))


def collect_actions(apps, now):
    """Dates order real commitments; no inferred fit scores or automatic follow-ups."""
    actions = []
    for index, app in enumerate(apps):
        if app["status"] in CLOSED:
            continue
        events = [e for e in pending_events(app) if datetime.fromisoformat(e["at"]).date() <= now.astimezone(datetime.fromisoformat(e["at"]).tzinfo).date() + timedelta(days=7)]
        for event in events:
            when = datetime.fromisoformat(event["at"])
            rank = (1 if when < now else 0) if event["kind"] != "suggested" else 3
            actions.append((rank, when, index, event))
        if not events and not app.get("needs_user") and app["status"] in CANDIDATES | {"assessment", "interview", "offer"} and app.get("next_action"):
            actions.append((4, now, index, None))
    return sorted(actions, key=lambda item: item[:3])


def action_html(app, index, event, workspace, now, compact=False):
    brief = app.get("brief", {})
    elapsed = event and datetime.fromisoformat(event["at"]) < now
    if event:
        stamp = date_label(event["at"], now, relative=True)
        label = "时间已过 · 请核实" if elapsed else KINDS[event["kind"]]
        event_name = f' · {escape(event["title"])}' if elapsed else ""
        meta = f'{stamp}{event_name} <span class="tag {"attention" if elapsed else ""}">{label}</span>'
        title = "核实这项安排的最新状态" if elapsed else event["title"]
    else:
        meta = "下一步"
        title = app.get("next_action", "查看岗位记录")
    context = ""
    if not compact:
        for label, value in (("推进理由", brief.get("reason")), ("准备重点", brief.get("preparation") if not elapsed else None), ("关键待核", brief.get("question"))):
            if value:
                context += f'<div class="context-line"><dt>{label}</dt><dd>{escape(value)}</dd></div>'
    materials = material_links(app, workspace)
    return f'''<article class="action {"secondary" if compact else "primary"}">
<p class="eyebrow">{meta}</p><h3>{escape(title)}</h3>
<p class="job-ref"><a href="#job-{index}">{escape(app['company'])} · {escape(app['role'])}</a></p>
{f'<dl class="context">{context}</dl>' if context else ''}
{f'<div class="material-links">{materials}</div>' if materials else ''}</article>'''


def opportunity_html(app, index, workspace, now):
    brief = app.get("brief", {})
    state = app["status"]
    group = "closed" if state in CLOSED else ("candidate" if state in CANDIDATES else "active")
    events = pending_events(app) if state not in CLOSED else []
    next_event = events[0] if events else None
    summary = escape(brief.get("reason") or brief.get("work") or "尚未记录岗位判断")
    question = f'<p class="question"><span>待核实</span>{escape(brief["question"])}</p>' if brief.get("question") and state not in CLOSED else ""
    action = app.get("next_action") or ("等待新反馈" if state in {"waiting", "submitted"} else "尚未记录下一步")
    if state in CLOSED:
        action = "记录已归档"
    timing = ""
    if next_event:
        expired = datetime.fromisoformat(next_event["at"]) < now
        timing = f'<p class="timing {"elapsed" if expired else ""}">{date_label(next_event["at"], now, True)} · {escape(next_event["title"])}{" · 时间已过，请核实" if expired else ""}</p>'
    checked = max((s["checked_at"] for s in app["sources"].values()), key=datetime.fromisoformat, default=None)
    checked_text = f'最近核验 {date_label(checked, now)}' if checked else "来源尚未登记"
    materials = material_links(app, workspace)
    source_rows = "".join(f'<li>{link(SOURCES[s["kind"]], s["locator"], workspace, False)} · {date_label(s["checked_at"], now)}<p>{escape(s["excerpt"])}</p><small>{escape(s["locator"])}</small></li>' for s in app["sources"].values())
    history = "".join(f'<li>{date_label(e["at"], now)} · {escape(e["title"])} · {KINDS[e["kind"]]} · {"已完成" if e.get("done") else "未标记完成"}</li>' for e in sorted(app["events"], key=lambda e: datetime.fromisoformat(e["at"])))
    submission = app.get("submission", {})
    submitted = date_label(submission["at"], now) if submission else "尚未提交"
    attachment = submission.get("resume_version") or submission.get("resume_unavailable_reason") or "尚无已发附件"
    details = ""
    work = f'<p class="work">{escape(brief["work"])}</p>' if brief.get("work") else ""
    for label, value in (("实际工作", brief.get("work")), ("准备重点", brief.get("preparation")), ("需要你参与", app.get("needs_user") if state not in CLOSED else None)):
        if value:
            details += f'<p><strong>{label}</strong> {escape(value)}</p>'
    return f'''<article class="opportunity" id="job-{index}" data-group="{group}">
<div class="opportunity-row"><div><h3>{escape(app['company'])}</h3><p class="role">{escape(app['role'])}</p>{work}
<p class="identity"><span class="tag">{STATUS[state]}</span>{escape(app.get('location', '地点待核实'))}</p></div>
<div class="assessment"><p>{summary}</p>{question}</div><div class="next-step"><p>{escape(action)}</p>{timing}</div></div>
<details><summary>资料与记录 <span>{checked_text}</span></summary><div class="record-body">
<div class="material-links">{materials or '<span class="muted">尚未关联材料</span>'}</div>{details}
<p class="muted">{escape(app['id'])} · {escape(app['project'])}</p>
<p>提交：{submitted}<br>实际附件：{escape(attachment)}</p>
{f'<h4>日程记录</h4><ul>{history}</ul>' if history else ''}<h4>信息来源</h4><ul>{source_rows or '<li>来源待补</li>'}</ul>
</div></details></article>'''


def render_dashboard(data, workspace, now=None):
    workspace = Path(workspace).resolve()
    now = now or datetime.now(timezone.utc)
    apps = data["applications"]
    active = [app for app in apps if app["status"] not in CLOSED]
    actions = collect_actions(apps, now)
    personal = [(i, app) for i, app in enumerate(apps) if app["status"] not in CLOSED and app.get("needs_user")]
    action_count = len(actions) + len(personal)
    nav = "".join(link(label, path, workspace) for label, path in (("目标与偏好", "PROFILE.md"), ("简历底稿", "resumes/source/master.md"), ("经历库", "records/facts.md")))
    if actions:
        rendered = [action_html(apps[i], i, event, workspace, now, compact=n > 0) for n, (_, _, i, event) in enumerate(actions[:3])]
        secondary = '<div class="up-next">' + ''.join(rendered[1:]) + '</div>' if len(rendered) > 1 else ''
        focus = f'<div class="focus-layout {"single" if len(rendered) == 1 else ""}">{rendered[0]}{secondary}</div>'
        if len(actions) > 3:
            extra = "".join(f'<li><a href="#job-{i}">{escape(apps[i]["company"])} · {escape(event["title"] if event else apps[i].get("next_action", "查看记录"))}</a>{" · " + date_label(event["at"], now, True) if event else ""}</li>' for _, _, i, event in actions[3:])
            focus += f'<details class="more-actions"><summary>还有 {len(actions) - 3} 项已登记事项</summary><ul>{extra}</ul></details>'
    elif personal:
        focus = ""
    else:
        title, description = ("从一个具体目标开始", "把已有简历或一条岗位说明交给助手，先完成当前最需要的一步。") if not apps else (("当前没有已登记的近期安排", "申请进展保留在下方。有新通知时，从对应岗位继续。") if active else ("当前没有推进中的申请", "历史记录已保留，可从中复用经历与准备材料。"))
        focus = f'<div class="empty-focus"><h3>{title}</h3><p>{description}</p><div class="material-links">{nav}</div></div>'
    if personal:
        tasks = "".join(f'<li><p>{escape(app["needs_user"])}</p><a href="#job-{i}">{escape(app["company"])} · {escape(app["role"])}</a></li>' for i, app in personal)
        focus += f'<div class="personal-tasks" role="region" aria-labelledby="personal-title"><h3 id="personal-title">需要你参与 · {len(personal)} 项</h3><ul>{tasks}</ul></div>'
    rows = "".join(opportunity_html(app, i, workspace, now) for i, app in enumerate(apps) if app["status"] not in CLOSED)
    rows += "".join(opportunity_html(app, i, workspace, now).replace('data-group="closed"', 'data-group="closed" hidden') for i, app in enumerate(apps) if app["status"] in CLOSED)
    opportunities = f'''<section class="opportunities" aria-labelledby="opportunity-title"><div class="section-heading"><h2 id="opportunity-title">值得继续看的机会</h2><span id="visible-count" aria-live="polite">当前 {len(active)} 条</span></div>
<div class="filters"><div class="tabs" aria-label="岗位范围"><button type="button" data-filter="current" aria-pressed="true">当前机会</button><button type="button" data-filter="candidate" aria-pressed="false">待申请</button><button type="button" data-filter="closed" aria-pressed="false">已结束</button><button type="button" data-filter="all" aria-pressed="false">全部</button></div>
<label class="search-label">查找岗位<input id="search" type="search" placeholder="企业、岗位或关键词" autocomplete="off"></label></div>
<div class="list-heading"><span>岗位与阶段</span><span>推进理由 · 关键疑问</span><span>下一步</span></div>
<div class="opportunity-list">{rows}</div><p id="empty" class="empty-list" {"hidden" if active else ""}>当前没有匹配的岗位，可切换范围查看。</p></section>''' if apps else ""
    css = Path(__file__).with_name("dashboard.css").read_text(encoding="utf-8")
    js = Path(__file__).with_name("dashboard.js").read_text(encoding="utf-8")
    demo_notice = '<p class="demo-notice">合成演示 · 企业、岗位、经历及日程均为虚构</p>' if data.get("demo") else ""
    return f'''{MARKER}
<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="referrer" content="no-referrer"><title>求职工作台 · job-prep-kit</title><style>{css}</style></head>
<body><main><header><div class="brand">JOB PREP KIT <span>个人求职工作区</span></div><nav aria-label="我的材料">{nav}</nav></header>{demo_notice}
<div class="intro"><div><h1>求职工作台</h1><p>先处理重要安排，再投入合适的机会。</p></div><p class="snapshot" data-generated="{now.isoformat()}">本地快照<br>{date_label(now.astimezone().isoformat(), now)}</p></div>
<p id="stale" class="stale" hidden>此快照不是今天生成的，日程标签以生成时为准。请更新记录并重新生成。</p>
<section aria-labelledby="focus-title"><div class="section-heading"><h2 id="focus-title">现在先做什么</h2><span>{f'{action_count} 项已登记事项' if action_count else '按当前记录'}</span></div>{focus}</section>
{opportunities}<footer><span>资料留在本地 · 来源与原件随岗位保留</span><span>记录更新后，重新生成并刷新本页。</span></footer>
</main><script>{js}</script></body></html>'''


def write_dashboard(workspace, data, output_dir=None):
    target = Path(output_dir or workspace) / "applications/dashboard.html"
    if target.exists() and not target.read_text(encoding="utf-8").startswith(MARKER):
        raise ValueError("dashboard.html 已有手写内容，未覆盖；请指定其他 --output-dir")
    content = render_dashboard(data, workspace)
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_suffix(".html.tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(target)
    return target
