"""Validate the local application ledger and derive readable views. No external writes."""
import argparse
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path

MARKER = "<!-- generated by job-prep-kit tracker; edit data.json -->"
STATES = {"candidate", "ready", "draft", "submitted", "assessment", "interview", "waiting", "offer", "rejected", "withdrawn", "signed"}
SOURCE_KINDS = {"employer", "school", "personal_notice", "community", "other"}


def timestamp(value):
    if not isinstance(value, str):
        raise ValueError("时间必须是带时区的字符串")
    parsed = datetime.fromisoformat(value)
    if parsed.tzinfo is None:
        raise ValueError("时间必须带时区，例如 2030-09-21T18:00:00+08:00")
    return parsed


def fields(value, path, names=()):
    if not isinstance(value, dict):
        raise ValueError(f"{path} 必须是对象")
    for name in names:
        if not isinstance(value.get(name), str) or not value[name].strip():
            raise ValueError(f"{path}.{name} 必须是非空字符串")


def validate(data):
    fields(data, "台账")
    if data.get("schema_version") != 1 or not isinstance(data.get("applications"), list):
        raise ValueError("需要 schema_version=1 和 applications 数组")
    ids = set()
    for index, app in enumerate(data["applications"]):
        path = f"applications[{index}]"
        fields(app, path, ("id", "company", "project", "role", "status"))
        if "next_action" in app and not isinstance(app["next_action"], str):
            raise ValueError(f"{path}.next_action 必须是字符串")
        for key in ("sources", "events"):
            if key not in app:
                raise ValueError(f"缺少字段 {key}")
        if app["id"] in ids:
            raise ValueError("岗位记录 id 为空或重复")
        ids.add(app["id"])
        if app["status"] not in STATES:
            raise ValueError(f"{app['id']}: 未知状态")
        sources = app["sources"]
        if not isinstance(sources, dict):
            raise ValueError("sources 必须是以来源 id 为键的对象")
        for source_id, source in sources.items():
            fields(source, f"{path}.sources.{source_id}", ("kind", "locator", "checked_at", "excerpt"))
            if source["kind"] not in SOURCE_KINDS:
                raise ValueError("来源需要 kind/locator/checked_at/excerpt")
            timestamp(source["checked_at"])
        submission = app.get("submission")
        if submission is not None:
            fields(submission, f"{path}.submission", ("at", "source"))
            version = submission.get("resume_version")
            missing = submission.get("resume_unavailable_reason")
            if bool(version) == bool(missing):
                raise ValueError(f"{path}.submission: 填 resume_version，或以 resume_unavailable_reason 明确说明历史附件缺失；不能同时填")
            fields(submission, f"{path}.submission", ("resume_version",) if version else ("resume_unavailable_reason",))
            timestamp(submission["at"])
            if sources.get(submission["source"], {}).get("kind") not in {"employer", "personal_notice"}:
                raise ValueError("提交凭证必须指向官网记录或本人发送/收到的凭证")
        if app["status"] in {"submitted", "assessment", "interview", "waiting", "offer", "signed"} and not submission:
            raise ValueError("流程中岗位必须有提交记录；未知历史先记 candidate 并写信息缺口")
        if "result" in app:
            fields(app["result"], f"{path}.result", ("source",))
        if app["status"] in {"offer", "signed", "rejected"}:
            result = app.get("result", {})
            if sources.get(result.get("source"), {}).get("kind") not in {"employer", "personal_notice"}:
                raise ValueError("录用、签约或淘汰必须有 result.source 关联正式结果；个人感觉不是结果")
        if not isinstance(app["events"], list) or not isinstance(app.get("choices", []), list):
            raise ValueError("events/choices 必须是数组")
        if any(not isinstance(choice, str) for choice in app.get("choices", [])):
            raise ValueError(f"{path}.choices 的每项必须是字符串")
        for event_index, event in enumerate(app["events"]):
            fields(event, f"{path}.events[{event_index}]", ("title", "at", "kind"))
            if "source" in event and not isinstance(event["source"], str):
                raise ValueError(f"{path}.events[{event_index}].source 必须是字符串")
            if "done" in event and not isinstance(event["done"], bool):
                raise ValueError("done 必须是 true/false，不能用字符串代替")
            if event["kind"] not in {"deadline", "scheduled", "suggested"}:
                raise ValueError("节点需要 title/at/kind；kind=deadline/scheduled/suggested")
            timestamp(event["at"])
            if event.get("notified_at"):
                timestamp(event["notified_at"])
            if event["kind"] != "suggested" and sources.get(event.get("source"), {}).get("kind") not in {"employer", "school", "personal_notice"}:
                raise ValueError("官方截止/安排必须关联企业、学校或个人通知来源")
    return data


def validate_workspace(workspace, data):
    validate(data)
    warnings = []
    for app in data["applications"]:
        submission = app.get("submission")
        if submission and submission.get("resume_unavailable_reason"):
            warnings.append(f"{app['id']}: 历史附件待补：{submission['resume_unavailable_reason']}")
    return warnings


def cell(value):
    return str(value or "—").replace("|", "\\|").replace("\r", " ").replace("\n", " ").replace("<", "&lt;").replace(">", "&gt;")


def render(data, now=None):
    validate(data)
    now = now or datetime.now(timezone.utc)
    apps = data["applications"]
    submitted = [a for a in apps if a.get("submission")]
    companies = len({(a["company"], a["project"]) for a in submitted})
    wishes = sum(len(a.get("choices", [])) for a in submitted)
    head = [MARKER, "", f"> 生成时间：{now.isoformat(timespec='seconds')}；统计按 company + project 去重。", ""]
    table = head + ["# 投递总表", "", f"已投企业/统一项目 {companies}；已投记录 {len(submitted)}；明确登记的志愿 {wishes}（未填不推断）。", "", "| ID | 企业/项目 | 岗位 | 状态 | 下一动作 |", "|---|---|---|---|---|"]
    timeline = head + ["# 时间轴", "", "| 时间 | 岗位ID | 节点 | 类型 | 完成 | 来源 |", "|---|---|---|---|---|---|"]
    today = head + ["# 投递日程", "", "先处理近期考核和截止，再看下一动作；建议时间不是官方截止。时间已过仅提示核实，不推断淘汰。", "", "## 逾期、今天与未来七天", ""]
    next_actions = []
    for app in apps:
        table.append("| " + " | ".join(cell(x) for x in (app["id"], app["company"] + "/" + app["project"], app["role"], app["status"], app.get("next_action"))) + " |")
        if (app.get("submission") or {}).get("resume_unavailable_reason"):
            next_actions.append(f"- 附件待补：{cell(app['id'])} {cell(app['submission']['resume_unavailable_reason'])}")
        if app.get("next_action") and app["status"] not in {"withdrawn", "rejected", "signed"}:
            next_actions.append(f"- {cell(app['id'])}：{cell(app['next_action'])}")
    events = sorted(((timestamp(e["at"]), a, e) for a in apps for e in a["events"]), key=lambda item: item[0])
    for when, app, event in events:
        source = app["sources"].get(event.get("source"), {})
        timeline.append("| " + " | ".join(cell(x) for x in (event["at"], app["id"], event["title"], event["kind"], "已完成" if event.get("done") else "待处理", source.get("locator", "助手建议"))) + " |")
        local_now = now.astimezone(when.tzinfo)
        if not event.get("done") and when.date() <= local_now.date() + timedelta(days=7) and app["status"] not in {"withdrawn", "rejected", "signed"}:
            label = "时间已过，核实状态" if when < now else ("今天" if when.date() == local_now.date() else "未来七天")
            today.append(f"- {label}：{cell(app['id'])} {cell(event['title'])}（{event['at']}，{event['kind']}）")
    today.extend(["", "## 下一动作", ""] + (next_actions or ["暂无待办。收到新通知后更新台账。"]))
    return {"投递总表.md": table, "时间轴.md": timeline, "投递日程.md": today}


def write_views(workspace, views):
    folder = Path(workspace) / "applications"
    for name in views:
        target = folder / name
        if target.exists() and not target.read_text(encoding="utf-8").startswith(MARKER):
            raise ValueError(f"拒绝覆盖手写文件 {name}；新工作区用 render --output-dir 指向新目录，核对后自行迁移。")
    folder.mkdir(parents=True, exist_ok=True)
    for name, lines in views.items():
        target = folder / name
        temporary = target.with_suffix(".md.tmp")
        temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
        temporary.replace(target)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["validate", "render"])
    parser.add_argument("--workspace", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, help="可选的视图工作区根目录；输出至其 applications 子目录")
    args = parser.parse_args()
    try:
        data = json.loads((args.workspace / "applications/data.json").read_text(encoding="utf-8"))
        for warning in validate_workspace(args.workspace, data):
            print("提醒：" + warning)
        if args.command == "render":
            write_views(args.output_dir or args.workspace, render(data))
        print("校验通过" if args.command == "validate" else "已生成三份视图；以 data.json 为准")
    except (ValueError, OSError, KeyError, TypeError) as exc:
        parser.exit(1, str(exc) + "\n")
